

###
POST http://localhost:18080/
Content-Type: application/json

{
    "id": 2,
    "title": "테스트 입니다.2",
    "order": 0,
    "completed": false,
    "url": "http://localhost:8080/2"
}


###
GET http://{{host}}:{{port}}/3

###
PATCH http://localhost:18080/{{id}}

###
DELETE http://localhost:18080/{{id}}

###
PATCH http://localhost:18080/{{id}}





